# import streamlit as st
# import openai
# import wikipedia
# def Query(question):
#     openai.api_key = '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'

#     response = openai.Completion.create(
#         model='text-davinci-002',
#         prompt=f'Q: {question}\nA:',
#         temperature=0.7,
#         max_tokens=1024,
#         top_p=1,
#         frequency_penalty=0,
#         presence_penalty=0
#     )
#     answer = response.choices[0].text.strip()

#     return answer
import openai

def Query(question):
    openai.api_key = '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' 
    response = openai.Completion.create(
        model='text-davinci-003',
        prompt=f'Q: {question}\nA:',
        temperature=0.7,
        max_tokens=1024,
        top_p=1,
        frequency_penalty=0,
        presence_penalty=0
    )
    answer = response.choices[0].text.strip()
    return answer
    keywords = [
    'education', 'learning', 'teaching', 'school', 'college', 'university',
    'student', 'classroom', 'curriculum', 'lesson', 'lecture', 'study', 'research',
    'academic', 'knowledge', 'scholarship', 'training', 'instruction', 'pedagogy',
    'academy', 'program', 'course', 'degree', 'credential', 'enrollment', 'assessment',
    'examination', 'homework', 'assignment', 'assessment', 'grading', 'grading',
    'grade', 'score', 'evaluation', 'performance', 'achievement', 'test', 'exam',
    'quiz', 'assessment', 'certification', 'accreditation', 'credentialing', 'learning',
    'outcome', 'syllabus', 'class', 'lecture', 'tutor', 'mentor', 'instructor',
    'professor', 'teacher', 'student', 'learner', 'educator', 'faculty', 'administration',
    'research', 'explain', 'what', 'how', 'explain in detail', 'publication', 'library', 'resource', 'study', 'program', 'scholar',
    'researcher', 'student', 'classmate', 'study', 'group', 'online', 'distance',
    'learning', 'virtual', 'e-learning', 'blended', 'instruction', 'coursework',
    'workshop', 'seminar', 'webinar', 'conference', 'workshop', 'seminar', 'webinar',
    'conference', 'workshop', 'seminar', 'webinar', 'conference', 'workshop', 'seminar',
    'webinar', 'conference', 'workshop', 'seminar', 'webinar', 'conference',
    'homework', 'assignment', 'project', 'research', 'paper', 'thesis', 'dissertation',
    'capstone', 'project-based', 'learning', 'competency-based', 'learning',
    'problem-based', 'learning', 'experiential', 'learning', 'learner-centered',
    'instruction', 'personalized', 'learning', 'adaptive', 'learning', 'individualized',
    'instruction', 'collaborative', 'learning', 'cooperative', 'learning',
    'peer', 'learning', 'social', 'learning', 'inclusive', 'education', 'diversity',
    'equity', 'access', 'inclusion', 'special', 'education', 'inclusive', 'classroom',
    'differentiated', 'instruction', 'universal', 'design', 'for', 'learning',
    'multicultural', 'education', 'global', 'education', 'international', 'education',
    'cross-cultural', 'learning', 'intercultural', 'competence', '21st', 'century',
    'skills', 'critical', 'thinking', 'creativity', 'communication', 'collaboration',
    'problem', 'solving', 'decision', 'making', 'information', 'literacy',
    'media', 'literacy', 'technology', 'literacy', 'global', 'competence',
    'leadership', 'skills', 'teamwork', 'resilience', 'adaptability', 'innovation',
    'flexibility', 'entrepreneurship', 'character', 'education', 'emotional', 'intelligence',
    'ethical', 'reasoning', 'cultural', 'intelligence', 'digital', 'citizenship',
    'financial', 'literacy', 'health', 'education', 'physical', 'education',
    'well-being', 'self-care', "lecture", "textbook",
    "note-taking",
    "research",
    "assignments",
    "exams",
    "homework",
    "reading",
    "classroom",
    "professor",
    "student",
    "curriculum",
    "syllabus",
    "study group",
    "study materials",
    "learning",
    "academic",
    "grades",
    "degree",
    "major",
    "minor",
    "program",
    "semester",
    "attendance",
    "participation",
    "lecture notes",
    "class discussion",
    "group project",
    "presentation",
    "study schedule",
    "library",
    "online resources",
    "research paper",
    "thesis",
    "dissertation",
    "graduation",
    "academic advisor",
    "office hours",
    "peer review",
    "faculty",
    "academic calendar",
    "coursework",
    "lab",
    "practical",
    "internship",
    "capstone",
    "electives",
    "academic support",
    "tutoring",
    "academic integrity",
    "plagiarism",
    "citation",
    "academic success",
    "time management",
    "test preparation",
    "notebooks",
    "pencils",
    "highlighters",
    "textbook rentals",
    "online learning",
    "distance education",
    "e-learning",
    "virtual classrooms",
    "educational technology",
    "study abroad",
    "scholarship",
    "financial aid",
    "student loans",
    "career development",
    "job prospects",
    "professional development",
    "networking",
    "resume",
    "cover letter",
    "interview preparation",
    "job search",
    "career fair",
    "internship opportunities",
    "job application",
    "job interview",
    "work experience",
    "employment prospects", "study tips",
    "study techniques",
    "study strategies",
    "study methods",
    "study habits",
    "study skills",
    "exam preparation",
    "test preparation",
    "homework help",
    "assignment help",
    "note-taking",
    "time management",
    "study resources",
    "study materials",
    "study guides",
    "study group",
    "online learning",
    "distance learning",
    "e-learning",
    "virtual classrooms",
    "educational technology",
    "research skills",
    "academic writing",
    "essay writing",
    "presentation skills",
    "critical thinking",
    "problem-solving",
    "self-directed learning",
    "active learning",
    "revision techniques",
    "memory techniques",
    "classroom participation",
    "peer collaboration",
    "test-taking strategies",
    "study schedule",
    "study planner",
    "study techniques for exams",
    "study techniques for finals",
    "study techniques for college",
    "study techniques for high school",
    "study techniques for university",
    "study techniques for online learning",
    "study techniques for distance learning",
    "study techniques for virtual classrooms",
    "study techniques for e-learning",
    "study techniques for academic success",
    "study techniques for better grades",
    "study techniques for effective learning",
    "mathematics",
    "science",
    "history",
    "geography",
    "english",
    "literature",
    "foreign languages",
    "computer science",
    "programming",
    "data science",
    "biology",
    "chemistry",
    "physics",
    "social sciences",
    "psychology",
    "sociology",
    "economics",
    "business studies",
    "accounting",
    "finance",
    "marketing",
    "management",
    "communication",
    "arts",
    "music",
    "fine arts",
    "performing arts",
    "physical education",
    "health education",
    "sports",
    "extracurricular activities",
    "academic competitions",
    "student organizations",
    "college admissions",
    "scholarships",
    "financial aid",
    "career planning",
    "job search",
    "internships",
    "resume writing",
    "interview preparation",
    "graduate school",
    "post-graduation",
    "study abroad",
    "student life",
    "time management",
    "stress management",
    "academic success",
    "personal development",
    "learning strategies",
    "educational resources",
    "educational websites",
    "online courses",
    "educational apps",
    "educational videos",
    "educational podcasts",
    "study hacks",
    "study techniques for visual learners",
    "study techniques for auditory learners",
    "study techniques for kinesthetic learners",
    "study techniques for different learning styles",
    "study techniques for memorization",
    "study techniques for problem-solving",
    "study techniques for critical thinking",
    "study techniques for active learning",
    "study techniques for self-directed learning",
    "study techniques for exam success",
    "study techniques for better retention",
    "study techniques for efficient learning", "reading comprehension",
    "critical reading",
    "vocabulary building",
    "academic goals",
    "study routine",
    "test anxiety",
    "online resources for studying",
    "homework tips",
    "online libraries",
    "plagiarism prevention",
    "academic integrity",
    "online forums for students",
    "distance learning tools",
    "educational software",
    "study aids",]
    filtered_answer = ''
    for keyword in keywords:
        if keyword in answer:
            filtered_answer = answer
            break

    return filtered_answer